const CACHE_NAME = 'runflow-v2';
const INITIAL_CACHE = [
  './',
  './index.html',
  './manifest.json'
];

// Install: Cache the initial shell
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => {
        return cache.addAll(INITIAL_CACHE);
      })
  );
});

// Fetch: Stale-while-revalidate strategy
// We serve from cache if available, but also fetch from network to update cache for next time.
// Also dynamically caches new resources (like the JS bundles generated by Vite).
self.addEventListener('fetch', event => {
  // Skip cross-origin requests (like Google Fonts/Auth) for complex caching, 
  // or handle them with a specific strategy if needed.
  // Here we focus on our app's assets.
  
  event.respondWith(
    caches.match(event.request).then(cachedResponse => {
      // Even if we have it in cache, we try to fetch fresh
      const fetchPromise = fetch(event.request).then(networkResponse => {
        // Check if valid response to cache
        if (networkResponse && networkResponse.status === 200 && networkResponse.type === 'basic') {
          const responseToCache = networkResponse.clone();
          caches.open(CACHE_NAME).then(cache => {
            cache.put(event.request, responseToCache);
          });
        }
        return networkResponse;
      }).catch(() => {
        // Network failed
        return cachedResponse; 
      });

      // Return cached response immediately if available (Fast), otherwise wait for network
      return cachedResponse || fetchPromise;
    })
  );
});

// Activate: Clean up old caches
self.addEventListener('activate', event => {
  const cacheWhitelist = [CACHE_NAME];
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cacheName => {
          if (cacheWhitelist.indexOf(cacheName) === -1) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});